# Generated by Django 4.1.1 on 2022-09-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_room_type_room_room_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseRoll',
            new_name='HouseRule',
        ),
    ]
