# Generated by Django 4.1 on 2022-10-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='chech_in',
            new_name='check_in',
        ),
    ]
