# Generated by Django 4.1 on 2022-10-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Accuracy',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Communication',
            new_name='communication',
        ),
    ]
