# Generated by Django 4.1 on 2022-10-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_accuracy_review_accuracy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cleanLiness',
            new_name='cleanliness',
        ),
    ]
